[package]
name = "url-cleaner-site"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0", features = ["json"] }
serde = "1.0.198"
tokio = { version = "1.37.0", features = ["macros", "rt"] }
url = { version = "2.5.0", features = ["serde"] }
url-cleaner = { path = "../url-cleaner" }
