[package]
name = "url-cleaner-site"
version = "0.1.0"
edition = "2021"
description = "A basic HTTP server and userscript to make using URL Cleaner in a browser easier."
repository = "https://github.com/Scripter17/url-cleaner-site"
keywords = ["url", "tracking", "paramaters", "telemetry", "consent"] # "telemetry" is specified because the freaks that use telemetry need to know people don't want or consent to it.
categories = []
license = "AGPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0", features = ["json"] }
serde = "1.0.198"
tokio = { version = "1.37.0", features = ["macros", "rt"] }
url = { version = "2.5.0", features = ["serde"] }
url-cleaner = { path = "../url-cleaner" }
