[package]
name = "url-cleaner-site"
version = "0.1.0"
edition = "2021"
description = "A basic HTTP server and userscript to make using URL Cleaner in a browser easier."
repository = "https://github.com/Scripter17/url-cleaner-site"
keywords = ["url", "tracking", "paramaters", "consent"]
categories = []
license = "AGPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.8"
rocket = { version = "0.5.1", features = ["json"] }
serde = "1.0.203"
serde_json = "1.0.118"
tokio = { version = "1.38.0", features = ["macros", "rt"] }
url = { version = "2.5.2", features = ["serde"] }
url-cleaner = { path = "../url-cleaner" }
